mmitv_back:
    resource: "@MmitvBackBundle/Resources/config/routing.yml"
    prefix:   /

mmitv_front:
    resource: "@MmitvFrontBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
