Mmitv\BackBundle\Entity\tweet:
    type: entity
    table: null
    repositoryClass: Mmitv\BackBundle\Entity\tweetRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        compteTweet:
            type: string
            length: '60'
            column: compte_tweet
        membreId:
            type: integer
            column: _membre_id
    lifecycleCallbacks: {  }
