Mmitv\BackBundle\Entity\videos:
    type: entity
    table: null
    repositoryClass: Mmitv\BackBundle\Entity\videosRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        lienVideos:
            type: string
            length: '100'
            column: lien_videos
        nomVideos:
            type: string
            length: '55'
            column: nom_videos
        plateformeVideos:
            type: string
            length: '20'
            column: plateforme_videos
        dureeVideos:
            type: time
            column: duree_videos
        debutVideos:
            type: time
            column: debut_videos
        finVideos:
            type: time
            column: fin_videos
        playlistId:
            type: integer
            column: _playlist_id
    lifecycleCallbacks: {  }
